name: Bernt
favicon: null
layout_spectrum: 0.06152
typography_spectrum: 0.36382
title: Bernt Blankholm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dee7ef'
    - '#121723'
    - '#435473'
    - '#6697cc'
    - '#ef7031'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
